shell = "zsh -c '{}'"

[[items]]
path = "https://github.com/tinted-theming/base16-vim"
name = "base16-vim"
themes-dir = "colors"

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hook = "tmux run 2> /dev/null && tmux source-file %f"
# hook = "tmux run 2> /dev/null && tmux source-file %f && tmux set-option -g status-style bg=default"
themes-dir = "colors"

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes-16/iterm2-applescripts"
hook = '''
command cp -f %f ~/Library/Application\ Support/iTerm2/Scripts/AutoLaunch.scpt \
    && ~/Code/dotfiles/tinty/convert_iterm2_colors.sh \
    && osascript ~/Library/Application\ Support/iTerm2/Scripts/AutoLaunch.scpt
'''
supported-systems = ["base16", "base24"]
